import { motion } from "framer-motion";
import {
  Accordion,
  AccordionContent,
  AccordionItem,
  AccordionTrigger,
} from "@/components/ui/accordion";

const faqs = [
  {
    q: "What can I actually build with Enter?",
    a: "You can build websites, web apps, dashboards, portfolios, e-commerce stores, landing pages, and more. Enter supports React, Tailwind CSS, and TypeScript out of the box.",
  },
  {
    q: "Is Enter free to start?",
    a: "Yes! Enter offers a free tier that lets you create up to 3 projects with basic AI features. Upgrade to Pro for unlimited projects and advanced capabilities.",
  },
  {
    q: "Do I need coding experience to use Enter?",
    a: "Not at all. Enter is designed for everyone\u2014from non-technical founders to experienced developers. Just describe what you want in plain language and Enter builds it.",
  },
  {
    q: "Do I own the code I build, and can I export it?",
    a: "Absolutely. You own 100% of the code generated by Enter. You can export it as a standard React/Vite project and host it anywhere you like.",
  },
  {
    q: "Does Enter handle hosting and deployment?",
    a: "Yes. Enter provides one-click deployment with SSL, CDN, and custom domain support. Your projects are deployed on a global edge network for maximum performance.",
  },
  {
    q: "How is my data privacy and security handled?",
    a: "Your data is encrypted at rest and in transit. We follow SOC 2 practices, and your code is never shared with other users or used to train models.",
  },
];

export default function FAQSection() {
  return (
    <section id="faq" className="bg-surface px-4 py-20 sm:px-6 lg:px-8">
      <div className="mx-auto flex max-w-4xl flex-col gap-10 md:flex-row md:gap-16">
        {/* Left heading */}
        <motion.div
          initial={{ opacity: 0, y: 16 }}
          whileInView={{ opacity: 1, y: 0 }}
          viewport={{ once: true }}
          transition={{ duration: 0.5 }}
          className="shrink-0 md:w-60"
        >
          <h2 className="text-3xl font-bold tracking-tight text-foreground sm:text-4xl">FAQ</h2>
          <p className="mt-2 text-sm text-muted-foreground">
            Everything you need to know about the product and billing.
          </p>
        </motion.div>

        {/* Accordion */}
        <motion.div
          initial={{ opacity: 0, y: 16 }}
          whileInView={{ opacity: 1, y: 0 }}
          viewport={{ once: true }}
          transition={{ duration: 0.5, delay: 0.1 }}
          className="flex-1"
        >
          <Accordion type="single" collapsible className="w-full">
            {faqs.map((faq, i) => (
              <AccordionItem key={i} value={`faq-${i}`} className="border-border">
                <AccordionTrigger className="text-left text-foreground hover:no-underline">
                  {faq.q}
                </AccordionTrigger>
                <AccordionContent className="text-muted-foreground">
                  {faq.a}
                </AccordionContent>
              </AccordionItem>
            ))}
          </Accordion>
        </motion.div>
      </div>
    </section>
  );
}
